apiVersion: v1
kind: Secret
metadata:
  imagename: DOCKER_IMAGE
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: deployment-one-to-roll-back
  labels:
    ttl-hours: '66'
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: just-a-test-deployment
        environment: dev
        origin: new-branch
    spec:
      containers:
        - name: just-a-test-deployment
          image: DOCKER_IMAGE
          imagePullPolicy: IfNotPresent
          env:
            - name: FEATURES_ON
              value: 'true'
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            timeoutSeconds: 4
          ports:
            - containerPort: 80
              name: httpport
