apiVersion: v1
kind: Service
metadata:
  name: image2
  annotations: 
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
  labels:
    name: image2
    team: flip
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 81
    name: http-proxy-protocol
  - port: 443
    targetPort: 444
    name: https-proxy-protocol
  selector:
    name: image2
    tier: frontend
