apiVersion: v1
kind: Service
metadata:
  name: www-icelandair-com-internal-test1
  labels:
    name: www-icelandair-com-internal-test1
    ttl-hours: '48'
spec:
  ports:
    - port: 10000
      name: http
  selector:
    name: www-icelandair-com-test1
    tier: frontend